site_name: Warmo's Stuff
site_url: http://warmolabs.tf
site_description: All of my random projects!
theme:
    name: material
    custom_dir: docs/overrides
    language: en
    palette:
        scheme: slate
        primary: custom
        accent: orange
    features:
        navigation.instant
        navigation.tracking
        navigation.sections
        navigation.tabs
        navigation.tabs.sticky
        toc.integrate
        search.highlight
    logo: images/icons/maze-cornea.png
    favicon: images/icons/maze-cornea-t.png
    font:
        text: Quantico
plugins:
    - social:
        cards_layout_options:
            font_family: Quantico
    - awesome-pages
    - blog:
        categories: true
        blog_dir: work
        archive: false
        authors: false
        post_readtime: false
    - search
    - open-in-new-tab
    - git-revision-date-localized
markdown_extensions:
#    - pymdownx.keys
#    - pymdownx.smartsymbols
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.blocks.caption
    - def_list
    - attr_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - md_in_html
    - tables
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
copyright: |
    &copy; 2025 <a href="https://github.com/Warmo"  target="_blank" rel="noopener">Jake W</a>
repo_url: https://github.com/Warmo/My-Site
extra_css:
    - stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-PPVP3M5SH8
#  social:
#    - icon: fontawesome/brands/bluesky
#      link: https://bsky.app/profile/warmo.bsky.social